### ISSUE TITLE
Not working on Windows 32bit

### ISSUE THREAD

**Issue by jorgestamatio** [megahertz/electron-log#28]
I've tried it on a Mac and it works like a charm but on a Windows 10, 32bits machine it doesn't create the log file. Any idea why? 
Thanks!

**Comment by megahertz** [comment]
- Do you use the latest version?
- Does it work on 64bit windows?
- Run your app from command line. Does the output contain any warning?

**Comment by birmjin10000** [comment]
Same thing happens on my Windows 10 64 bit machine.

**Comment by megahertz** [comment]
Also, you can try to set silly log level for file transport and check if log is created.

**Comment by megahertz** [comment]
@jorgestamatio @birmjin10000 Do you use webpack? There was a bug which is related to the latest webpack version which is fixed. Anyway, try the latest version.

**Comment by jorgestamatio** [comment]
Hi, yes I use the [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate) which uses webpack. I've tried installing version 2.2.2 and still no luck. I'm not sure how to run the built app from the command line on Windows so i cannot say if there's any warning. Haven't tried the silly log.

**Comment by megahertz** [comment]
@jorgestamatio Just follow the steps you follow on other operating systems to run from console:
1. Build unpacked application
2. open windows console, then: `c:\path\to\unpacked-app\YourApp.exe`

**Comment by jorgestamatio** [comment]
Oh ok, it does log to the terminal but it logs:
[warn] electron-log.transports.file: Could not set a log file
I've also tried the silly log and still nothing

**Comment by megahertz** [comment]
@jorgestamatio try to set appName property of file transport

**Comment by jorgestamatio** [comment]
I did, i set it to another name, should I try setting the same name?

**Comment by megahertz** [comment]
Yes, try to set it to your app's name. Also you can try to disable DefinePlugin in your webpack config.

**Comment by jorgestamatio** [comment]
I've set the appName and nothing. 
I didn't disable the DefinePlugin since I'm not sure exactly how the boilerplate uses it and the build crashes if I remove it from the config. I'm new to electron development and all of this webpack config is a bit overwhelming. 
Is it possible is due to that? Isn't it just a way to define environments?

**Comment by megahertz** [comment]
Check in your code what values are stored in USERPROFILE proc.env. Is it contain APPDATA and USERPROFILE keys?

**Comment by jorgestamatio** [comment]
No, there's no keys for APPDATA nor USERPROFILE.

**Comment by megahertz** [comment]
So, you can:
- disable DefinePlugin (or something else which strips environment variables)
- set log.transports.file.file manually on windows

**Comment by jorgestamatio** [comment]
Creating the file manually worked, good enough for me!
